// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entities

import (
	"time"
)

const TableNameOrder = "orders"

// Order mapped from table <orders>
type Order struct {
	ID        int32      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true" json:"id"`
	UserID    int32      `gorm:"column:user_id;type:integer;not null" json:"user_id"`
	ProductID int32      `gorm:"column:product_id;type:integer;not null" json:"product_id"`
	Quantity  int32      `gorm:"column:quantity;type:integer;not null" json:"quantity"`
	OrderDate *time.Time `gorm:"column:order_date;type:timestamp without time zone;default:CURRENT_TIMESTAMP" json:"order_date"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
