// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entities

import (
	"time"
)

const TableNamePayment = "payments"

// Payment mapped from table <payments>
type Payment struct {
	ID          int32      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true" json:"id"`
	UserID      int32      `gorm:"column:user_id;type:integer;not null" json:"user_id"`
	ProductID   int32      `gorm:"column:product_id;type:integer;not null" json:"product_id"`
	Amount      float64    `gorm:"column:amount;type:numeric(10,2);not null" json:"amount"`
	PaymentDate *time.Time `gorm:"column:payment_date;type:timestamp without time zone;default:CURRENT_TIMESTAMP" json:"payment_date"`
}

// TableName Payment's table name
func (*Payment) TableName() string {
	return TableNamePayment
}
