// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entities

import (
	"time"
)

const TableNameStock = "stock"

// Stock mapped from table <stock>
type Stock struct {
	ID          int32      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true" json:"id"`
	ProductID   int32      `gorm:"column:product_id;type:integer;not null" json:"product_id"`
	Quantity    int32      `gorm:"column:quantity;type:integer;not null" json:"quantity"`
	LastUpdated *time.Time `gorm:"column:last_updated;type:timestamp without time zone;default:CURRENT_TIMESTAMP" json:"last_updated"`
}

// TableName Stock's table name
func (*Stock) TableName() string {
	return TableNameStock
}
