// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbmodels

import (
	"time"
)

const TableNameProduct = "products"

// Product mapped from table <products>
type Product struct {
	ID          int32      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true" json:"id"`
	Name        string     `gorm:"column:name;type:character varying(255);not null" json:"name"`
	Description *string    `gorm:"column:description;type:text" json:"description"`
	Price       float64    `gorm:"column:price;type:numeric(10,2);not null" json:"price"`
	CreatedAt   *time.Time `gorm:"column:created_at;type:timestamp without time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   *time.Time `gorm:"column:updated_at;type:timestamp without time zone;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Product's table name
func (*Product) TableName() string {
	return TableNameProduct
}
